version: '3.8'

services:
  petstaff-landing:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petstaff-landing-page
    volumes:
      - ./build:/app/build
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped